application: missy-go
version: 1
runtime: python
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /styles
  static_dir: styles

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /custom404
  static_dir: 404/static

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  #login: admin

- url: .*
  script: main.py


